### ISSUE TITLE
Buggy forum thread

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct.net-website-bugs#50]
Something's gone wrong with this forum thread: https://www.construct.net/en/forum/construct-3/how-do-i-8/how-do-i-get-c2-project-to-bui-139019

There's some kind of caching problem - I accidentally double-posted because my reply didn't immediately appear, but then it showed two, so I deleted one. Now it shows one post with a deleted reply on PRD-VM-WEB-1 but both replies active on PRD-VM-WEB-2.

It shows two pages in the thread, but clicking page 2 stays on the first page.

**Comment by phillscirra** [comment]
Thanks Ash. Could be a little awkward to track down if it is a caching problem, but will give it a go.  What immediately springs to mind is that it could be either a glitch server side, or chrome deciding to serve you something from it's local cache, for whatever reason, maybe because the internet glitched out for a moment or was on a go-slow.  We may be able to try a few things to make it a little more consistent in behaviour.

**Comment by TomGullen** [comment]
Appears to of resolved itself - have made caching improvements so might now be fixed.
