### ISSUE TITLE
[Enhancement] Link Construct 3 Changelog To Construct 3 Bugs Page

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct.net-website-bugs#79]
## Description

I'd like to suggest linking things found in a typical [Construct 3 changelog](https://www.construct.net/en/make-games/releases/beta/r141), to the related issue on the [Construct 3 Github page](https://github.com/Scirra/Construct-3-bugs/issues) (if available). Currently there is no clear link to the Construct 3 bugs page and implementing this could help people, to not only find it but also see a proper issue report.

The way this could be implemented is fully up to you guys but I think keeping it simple like in the example below, would be quick and easy to work with.

## Example
![image](https://user-images.githubusercontent.com/15656049/54133261-0aa3ff80-4416-11e9-8857-71675caf9542.png)

**Comment by AshleyScirra** [comment]
This is already possible with the existing release system, but we don't use it because it's sometimes irrelevant or misleading, or only partially applicable, or involves multiple reports, etc. Besides surely for the typical user, the only important thing is that it got fixed? There's also [existing lists of issues categorised by release](https://github.com/Scirra/Construct-3-bugs/milestones?state=closed).

**Comment by TheRealDannyyy** [comment]
Cool, totally forgot about the milestone list.

> Besides surely for the typical user, the only important thing is that it got fixed?

I guess that's true. This idea mainly came into my mind after seeing some other unrelated changelogs doing this. Although since you guys simplify the titles, it might just end up being additional work.

In the end I still think having some sort of link between these two sites, would be a nice to have.
